#!/bin/bash

dirTre=/home/root
awk '{ print $2" "$4" "$6}' /var/log/hermes/lectures.txt | cut -d "." -f 1-3 | grep "^[0-9][0-9].[0-9][0-9][[:space:]][0-9][0-9].[0-9][0-9][[:space:]][0-9][0-9]:[0-9][0-9]:[0-9][0-9]$" > $dirTre/lectures.txt && cd $dirTre && gnuplot "plot" && python mail.py && rm *.eps
